#!/usr/bin/env bash
# This script displays information about subdomain(s)
display_subd_info () {
    if [ $# -lt 1 ] 
    then
        exit 0
    elif [ $# -lt 2 ] 
    then
        subdomains=("www" "lb-01" "web-01" "web-02")
        for domain in "${subdomains[@]}"
        do
            answer=$(dig "$domain"."$1" | awk ' NR==14 ')
            record=$(echo "$answer" | awk -F"\t" '{print $4}')
            ip=$(echo "$answer" | awk -F"\t" '{print $5}')
            echo "The subdomain $domain is a $record record and points to $ip"
        done
    else
        answer=$(dig "$2"."$1" | awk ' NR==14 ')
        record=$(echo "$answer" | awk -F"\t" '{print $4}')
        ip=$(echo "$answer" | awk -F"\t" '{print $5}')
        echo "The subdomain $2 is a $record record and points to $ip"
    fi  
}

if [ $# -eq 2 ]
then
    display_subd_info "$1" "$2"
else
    display_subd_info "$1"
fi
