#!/usr/bin/env bash
# This script transfers a file from our client to a server using scp
# It accepts 4 parameters: path to file, ip, username, path to ssh key
if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    ssh -i "$4" "$3"@"$2" '[ -d ~/ ]'
    home_exists="$?"

    if [ "$home_exists" -ne 0 ]
    then
        ssh -i "$4" "$3"@"$2" 'mkdir -p /home/"$3"'
    fi
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":/home/"$3"
fi
