#!/usr/bin/env bash
# This script transfers a file from our client to a server using scp
# It accepts 4 parameters: path to file, ip, username, path to ssh key
if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/ -i "$4"
fi
