#!/usr/bin/env bash
# This script installs and configures nginx in a new Ubuntu server
sudo apt update
sudo apt install nginx -y
echo "Hello World!" | sudo tee -a /var/www/html/index.html
sudo /etc/init.d/nginx restart
