#!/usr/bin/env bash
# This script installs and configures nginx in a new Ubuntu server
sudo apt update

sudo apt install nginx -y

echo "Hello World!" | sudo tee -a /var/www/html/index.html

sudo sed -i.bak '/server_name _;/a \ \
\
        location \/redirect_me {\
                rewrite ^\/redirect_me$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\
        }' /etc/nginx/sites-available/default

sudo /etc/init.d/nginx restart
