#!/usr/bin/env bash
# This script installs and configures nginx in a new Ubuntu server
sudo apt update

sudo apt install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html

if grep -q  "rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
then
    echo "Redirect present"
else
    sudo sed -i.bak '/server_name _;/a \        rewrite ^\/redirect_me$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
fi

sudo /etc/init.d/nginx restart
