#!/usr/bin/env bash
# This script installs and configures HAProxy on a server
# Installing HAProxy using a dedicated PPA
sudo apt update
sudo apt install haproxy -y

if grep -q "frontend my_frontend" /etc/haproxy/haproxy.cfg
then
    :
else
    sudo sed -i '$a\
frontend my_frontend\
        bind *:80\
        default_backend my_backend\
' /etc/haproxy/haproxy.cfg
fi

if grep -q "^backend my_backend" /etc/haproxy/haproxy.cfg
then
    :
else
    sudo sed -i '$a\backend my_backend\
        balance roundrobin\
        server server1 3.90.85.174:80 check\
        server server2 100.26.159.203:80 check\
' /etc/haproxy/haproxy.cfg
fi

sudo /etc/init.d/haproxy restart
