#!/usr/bin/env bash
# This script installs and configures HAProxy on a server
# Installing HAProxy using a dedicated PPA
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get update
sudo apt-get install haproxy=2.8\* -y

if grep -q "frontend my_frontend" /etc/haproxy/haproxy.cfg
then
    :
else
    sudo sed -i '35a\frontend my_frontend\
        bind *:80\
        default_backend my_backend\
' /etc/haproxy/haproxy.cfg
fi

if grep -q "^backend my_backend" /etc/haproxy/haproxy.cfg
then
    :
else
    sudo sed -i '39a\backend my_backend\
        balance roundrobin\
        server server1 3.90.85.174:80 check\
        server server2 100.26.159.203:80 check\
' /etc/haproxy/haproxy.cfg
fi

sudo /etc/init.d/haproxy restart
