#!/usr/bin/env bash
# This script fixes nginx server issues in a server
sudo apt update
sudo apt install nginx -y
sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
