#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd
file="/etc/passwd"
while IFS= read -r line || [ -n "$line" ]
do
    IFS=$":"
    read -a array <<< "$line"
    echo "The user ${array[0]} is part of the ${array[3]} gang, lives in ${array[5]} and rides ${array[6]}. ${array[2]}'s place is protected by the passcode ${array[1]}, more info about the user here: ${array[0]}"
done < "$file"
IFS=$' \t\n'
