#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but diplays "Hi" on 9th iter
i=0
while (( i < 10 ))
do
    echo "Best School"
    if [ $i -eq 8 ]
    then
        echo "Hi"
    fi
    (( i++ ))
done
