#!/usr/bin/env bash
# This script runs whoami with the username passed as argument

orig_user=$(whoami)

if grep -q "$1" /etc/passwd
then
    :
else
    useradd "$1"
fi

su "$1" -c 'whoami'
su - "$orig_user"
